// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvptdktrtpetwmdfnagt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2cHRka3RydHBldHdtZGZuYWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTY5NTcsImV4cCI6MjA2NTY5Mjk1N30.l1u4vh0UxzRKp1an7X1_UFguiArtjOLJVPbHsqBNzPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);